# -*- coding: utf-8 -*-
"""Client.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SVV7c6odv6ks0cjKeCzgc_EwwDUgHzvG
"""

!pip -q install requests
import time, json, random, requests

def send_mock(
    url="http://177.44.248.27:5000/dados",
    lat=-29.4687, lon=-51.8153,
    speed=0.0, sats=7,
    n=5, interval=2.0, jitter=5
):
    """Envia n POSTs com JSON simulando o ESP32."""
    for i in range(n):
        dlat = (random.uniform(-1, 1) * jitter) * 1e-5
        dlon = (random.uniform(-1, 1) * jitter) * 1e-5
        payload = {
            "device": "esp32_gps",
            "lat": round(lat + dlat, 6),
            "lon": round(lon + dlon, 6),
            "speed": round(speed, 2),
            "sats": int(sats),
            "ts": int(time.time()*1000)
        }
        try:
            r = requests.post(url, json=payload, timeout=8)
            print(f"[{i+1}/{n}] {r.status_code} -> {r.text.strip()} :: {json.dumps(payload)}")
        except Exception as e:
            print(f"[{i+1}/{n}] ERRO: {e}")
        if i < n-1:
            time.sleep(interval)

print("Pronto! Use send_mock(...) na próxima célula.")

send_mock(n=10, interval=2, jitter=5)